
export const ADD_POST = 'ADD-POST';
export const SET_USER_PROFILE = 'SET-USER-PROFILE';
export const DELETE_USER_PROFILE = 'DELETE-USER-PROFILE';
export const SET_STATUS = 'SET-STATUS';
export const DELETE_POST = 'DELETE-POST';
export const SAVE_PHOTO_SUCCESS = 'SAVE-PHOTO-SUCCESS';
export const LOAD_PHOTO_SUCCESS = 'LOAD-PHOTO-SUCCESS';
export const SAVE_DATA_SUCCESS = 'SAVE-DATA-SUCCESS';